Change static rating stars with dynamic rating component
marwinburesch/moviescout pull request #24
Opened 2021-08-27 13:50 UTC by ChristianSeelemann

Deployment: https://review-ratingcomponent-nruzhnx.herokuapp.com/

2021-08-30 07:47 UTC, ChristianSeelemann commented
Deployment should be working now.

2021-08-31 12:35 UTC, phlgr requested changes

2021-08-31 12:35 UTC, phlgr commented on src/app/components/Card/Card.module.css
> +}
Please remove this margin as it moves the stars down.

2021-08-31 12:35 UTC, phlgr commented on src/app/components/Card/Card.tsx
>        <section>
Please add a small padding to this padding to create some space between the border and the text/rating

2021-09-01 07:47 UTC, phlgr approved these changes

2021-09-01 08:06 UTC, merged