Search page
marwinburesch/moviescout pull request #25
Opened 2021-08-27 15:02 UTC by dimas1976

https://review-searchpage-4ayp5adgahqj.herokuapp.com/search

2021-08-30 09:23 UTC, marwinburesch requested changes
Excellent work, thank you! ☔

2021-08-30 09:23 UTC, marwinburesch commented on src/app/pages/Search/Search.stories.tsx
> +export const SearchPage = (): JSX.Element => <Search />;
We decided, that we don't really need stories for our pages. Please remove the file

2021-08-30 09:23 UTC, marwinburesch commented on src/app/pages/Search/Search.tsx
> +        <p>Search Results(3)</p>
I'd separate `SearchBar`  from `TagGroup`

2021-08-30 09:23 UTC, marwinburesch commented on src/app/pages/Search/Search.module.css
> +  width: 100vw;
Is there a way to not set this property anywhere on lower leves than `#app` or the main grid for this page?
We might have to set a `max-width` for `TagGroup`

2021-08-31 12:27 UTC, phlgr requested changes

2021-08-31 12:27 UTC, phlgr commented on src/app/pages/Search/Search.tsx
> +        {mockCards?.map((mockCard) => (
```suggestion
        {mockCards && mockCards.map((mockCard) => (
```

2021-08-31 12:27 UTC, phlgr commented on src/app/pages/Search/Search.module.css
> +.cards {
whitespace missing

2021-08-31 12:27 UTC, phlgr commented on src/app/pages/Search/Search.module.css
> +}
You could move this property to the `.cards` class

2021-09-01 07:59 UTC, phlgr approved these changes

2021-09-01 07:59 UTC, marwinburesch approved these changes

2021-09-01 08:04 UTC, merged