Discoverpage
marwinburesch/moviescout pull request #26
Opened 2021-08-27 15:04 UTC by christophschmitz

Discover page of Moviescout

[Deployment link](https://review-discoverpage-eayzyyh4rp.herokuapp.com/discover)

2021-08-30 08:10 UTC, marwinburesch requested changes
Thank you very much ☔

2021-08-30 13:34 UTC, marwinburesch requested changes
Cheers! Just one more thing D:

2021-08-30 13:34 UTC, marwinburesch commented on src/app/pages/Discover/Discover.tsx
> +          mockMovies.map((movie) => <Card key={movie.title} {...movie} />)}
`onBookmarkClick` should get assigned here inside the `.map`, aim for a `handleBookmarkClick`. We won't get this from our API later

2021-08-30 13:48 UTC, marwinburesch requested changes
Cheers 🐘

2021-08-30 13:48 UTC, marwinburesch commented on src/app/pages/Discover/Discover.module.css
> +  grid-template-columns: 1fr 1fr;
Let's have this be responsive. It should be `1fr` on iPhone 5 and then scale up to have two or more rows if it fits

2021-08-31 12:16 UTC, phlgr approved these changes
LGTM 🎆

2021-08-31 13:09 UTC, marwinburesch approved these changes

2021-09-01 07:56 UTC, merged