Add hook useSearchMovies
marwinburesch/moviescout pull request #43
Opened 2021-09-01 13:46 UTC by dirkzukunft

2021-09-01 14:43 UTC, phlgr requested changes

2021-09-01 14:43 UTC, phlgr commented on src/app/hooks/useSearchMovies.ts
> +  refetch: () => void;
Please reconsider your naming and what needs to be returned. I don't think you will need the refetch.

2021-09-01 14:43 UTC, phlgr commented on src/app/pages/Search/Search.tsx
> +  const [searchQuery, setSearchQuery] = useState<string>('');
One state would be sufficient as the fetch onChange is okay.

2021-09-03 14:23 UTC, marwinburesch approved these changes

2021-09-06 09:53 UTC, phlgr approved these changes

2021-09-06 09:53 UTC, merged